project:
  type: website

website:
  title: "Music"
  navbar:
    background: primary
    right:
      - icon: github
        href: https://github.com/miriamheiss/miriam-blog
      - icon: instagram
        href: https://www.instagram.com/heiss.miriam/?hl=en
      - icon: youtube
        href: https://www.youtube.com/@MiriamHeiss
      - icon: music-note-beamed
        href: https://musescore.com/user/48858879
    left: 
      - posts.qmd
      - about.qmd
      - text: "Student Portfolio"
        menu: 
          - digital-portfolio/FCS208-byui.qmd
          - digital-portfolio/HUM110-byui.qmd
          - digital-portfolio/ENG102-asu.qmd
          - digital-portfolio/HST109-asu.qmd
          - digital-portfolio/POLSC110.qmd
      
  
          
    
format:
  html:
    theme: 
      - flatly
      - styles.scss
    highlight-style: breezedark
    toc: true
    #title-block-banner-color: "#ffffff"
  